//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP.SD.SalesSupport.LAW.Models {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LAWResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LAWResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EP.SD.SalesSupport.LAW.Models.LAWResource", typeof(LAWResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 三代主管 的當地語系化字串。
        /// </summary>
        public static string 三代主管 {
            get {
                return ResourceManager.GetString("三代主管", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳資料錯誤明細 的當地語系化字串。
        /// </summary>
        public static string 上傳資料錯誤明細 {
            get {
                return ResourceManager.GetString("上傳資料錯誤明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上月總累計未結案件 的當地語系化字串。
        /// </summary>
        public static string 上月總累計未結案件 {
            get {
                return ResourceManager.GetString("上月總累計未結案件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上次電催日期 的當地語系化字串。
        /// </summary>
        public static string 上次電催日期 {
            get {
                return ResourceManager.GetString("上次電催日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明：1‧不提供刪除功能，以防已建資料查無造成資料錯誤。 的當地語系化字串。
        /// </summary>
        public static string 不提供刪除功能 {
            get {
                return ResourceManager.GetString("不提供刪除功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不變動 的當地語系化字串。
        /// </summary>
        public static string 不變動 {
            get {
                return ResourceManager.GetString("不變動", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※不變動 的當地語系化字串。
        /// </summary>
        public static string 不變動2 {
            get {
                return ResourceManager.GetString("不變動2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主管 的當地語系化字串。
        /// </summary>
        public static string 主管 {
            get {
                return ResourceManager.GetString("主管", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主管照會單編號 的當地語系化字串。
        /// </summary>
        public static string 主管照會單編號 {
            get {
                return ResourceManager.GetString("主管照會單編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 之計算，設定前請先確認！ 的當地語系化字串。
        /// </summary>
        public static string 之計算設定前請先確認 {
            get {
                return ResourceManager.GetString("之計算設定前請先確認", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 95-98年度案件統計表 的當地語系化字串。
        /// </summary>
        public static string 九五九八年度案件統計表 {
            get {
                return ResourceManager.GetString("九五九八年度案件統計表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人員 的當地語系化字串。
        /// </summary>
        public static string 人員 {
            get {
                return ResourceManager.GetString("人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 例如選擇 97 年，則報表合併計算欄位年度為 95 ~ 97 年，其餘年度仍各自計算與顯示。 的當地語系化字串。
        /// </summary>
        public static string 例如選擇97年 {
            get {
                return ResourceManager.GetString("例如選擇97年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改契撤變原因 的當地語系化字串。
        /// </summary>
        public static string 修改契撤變原因 {
            get {
                return ResourceManager.GetString("修改契撤變原因", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改承辦單位 的當地語系化字串。
        /// </summary>
        public static string 修改承辦單位 {
            get {
                return ResourceManager.GetString("修改承辦單位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改經辦人 的當地語系化字串。
        /// </summary>
        public static string 修改經辦人 {
            get {
                return ResourceManager.GetString("修改經辦人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改經辦人員 的當地語系化字串。
        /// </summary>
        public static string 修改經辦人員 {
            get {
                return ResourceManager.GetString("修改經辦人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人資料 的當地語系化字串。
        /// </summary>
        public static string 個人資料 {
            get {
                return ResourceManager.GetString("個人資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        public static string 停用 {
            get {
                return ResourceManager.GetString("停用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 元 的當地語系化字串。
        /// </summary>
        public static string 元 {
            get {
                return ResourceManager.GetString("元", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司 的當地語系化字串。
        /// </summary>
        public static string 公司 {
            get {
                return ResourceManager.GetString("公司", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司總計 的當地語系化字串。
        /// </summary>
        public static string 公司總計 {
            get {
                return ResourceManager.GetString("公司總計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他 的當地語系化字串。
        /// </summary>
        public static string 其他 {
            get {
                return ResourceManager.GetString("其他", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他欄位 的當地語系化字串。
        /// </summary>
        public static string 其他欄位 {
            get {
                return ResourceManager.GetString("其他欄位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他規費 的當地語系化字串。
        /// </summary>
        public static string 其他規費 {
            get {
                return ResourceManager.GetString("其他規費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分期 的當地語系化字串。
        /// </summary>
        public static string 分期 {
            get {
                return ResourceManager.GetString("分期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分機 的當地語系化字串。
        /// </summary>
        public static string 分機 {
            get {
                return ResourceManager.GetString("分機", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分機號碼 的當地語系化字串。
        /// </summary>
        public static string 分機號碼 {
            get {
                return ResourceManager.GetString("分機號碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分機號碼；格式錯誤 的當地語系化字串。
        /// </summary>
        public static string 分機號碼格式錯誤 {
            get {
                return ResourceManager.GetString("分機號碼格式錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印存證信函設定步驟說明 的當地語系化字串。
        /// </summary>
        public static string 列印存證信函設定步驟說明 {
            get {
                return ResourceManager.GetString("列印存證信函設定步驟說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利息 的當地語系化字串。
        /// </summary>
        public static string 利息 {
            get {
                return ResourceManager.GetString("利息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利息天數 的當地語系化字串。
        /// </summary>
        public static string 利息天數 {
            get {
                return ResourceManager.GetString("利息天數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利息天數與利息為系統計算，不須輸入! 的當地語系化字串。
        /// </summary>
        public static string 利息天數與利息為系統計算不須輸入 {
            get {
                return ResourceManager.GetString("利息天數與利息為系統計算不須輸入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利息訖日 的當地語系化字串。
        /// </summary>
        public static string 利息訖日 {
            get {
                return ResourceManager.GetString("利息訖日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利息起日 的當地語系化字串。
        /// </summary>
        public static string 利息起日 {
            get {
                return ResourceManager.GetString("利息起日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利息起迄日期有誤 的當地語系化字串。
        /// </summary>
        public static string 利息起迄日期有誤 {
            get {
                return ResourceManager.GetString("利息起迄日期有誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 利率 的當地語系化字串。
        /// </summary>
        public static string 利率 {
            get {
                return ResourceManager.GetString("利率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 刪除排序年度後，請(需)重新設定該年度排序! 的當地語系化字串。
        /// </summary>
        public static string 刪除排序年度後 {
            get {
                return ResourceManager.GetString("刪除排序年度後", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 前案情形 的當地語系化字串。
        /// </summary>
        public static string 前案情形 {
            get {
                return ResourceManager.GetString("前案情形", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 剩餘結欠金額 的當地語系化字串。
        /// </summary>
        public static string 剩餘結欠金額 {
            get {
                return ResourceManager.GetString("剩餘結欠金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入 的當地語系化字串。
        /// </summary>
        public static string 匯入 {
            get {
                return ResourceManager.GetString("匯入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出報表 的當地語系化字串。
        /// </summary>
        public static string 匯出報表 {
            get {
                return ResourceManager.GetString("匯出報表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 區塊排序設定 的當地語系化字串。
        /// </summary>
        public static string 區塊排序設定 {
            get {
                return ResourceManager.GetString("區塊排序設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 協理 的當地語系化字串。
        /// </summary>
        public static string 協理 {
            get {
                return ResourceManager.GetString("協理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 協理系 的當地語系化字串。
        /// </summary>
        public static string 協理系 {
            get {
                return ResourceManager.GetString("協理系", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 受理案件 的當地語系化字串。
        /// </summary>
        public static string 受理案件 {
            get {
                return ResourceManager.GetString("受理案件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只能選能一位成員 的當地語系化字串。
        /// </summary>
        public static string 只能選能一位成員 {
            get {
                return ResourceManager.GetString("只能選能一位成員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 合併年度預設為 95 年起至所選擇年度，為連續且不可間斷！ 的當地語系化字串。
        /// </summary>
        public static string 合併年度預設為95年起至所選擇年度 {
            get {
                return ResourceManager.GetString("合併年度預設為95年起至所選擇年度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計未結總數 的當地語系化字串。
        /// </summary>
        public static string 合計未結總數 {
            get {
                return ResourceManager.GetString("合計未結總數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string 名稱 {
            get {
                return ResourceManager.GetString("名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (含續佣抵結欠) 的當地語系化字串。
        /// </summary>
        public static string 含續佣抵結欠 {
            get {
                return ResourceManager.GetString("含續佣抵結欠", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string 啟用 {
            get {
                return ResourceManager.GetString("啟用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用狀態 的當地語系化字串。
        /// </summary>
        public static string 啟用狀態 {
            get {
                return ResourceManager.GetString("啟用狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        public static string 單位 {
            get {
                return ResourceManager.GetString("單位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 團隊 的當地語系化字串。
        /// </summary>
        public static string 團隊 {
            get {
                return ResourceManager.GetString("團隊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 團隊名稱 的當地語系化字串。
        /// </summary>
        public static string 團隊名稱 {
            get {
                return ResourceManager.GetString("團隊名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 團隊排序 的當地語系化字串。
        /// </summary>
        public static string 團隊排序 {
            get {
                return ResourceManager.GetString("團隊排序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 團隊明細 的當地語系化字串。
        /// </summary>
        public static string 團隊明細 {
            get {
                return ResourceManager.GetString("團隊明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行人員 的當地語系化字串。
        /// </summary>
        public static string 執行人員 {
            get {
                return ResourceManager.GetString("執行人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行無實益 的當地語系化字串。
        /// </summary>
        public static string 執行無實益 {
            get {
                return ResourceManager.GetString("執行無實益", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行程序 的當地語系化字串。
        /// </summary>
        public static string 執行程序 {
            get {
                return ResourceManager.GetString("執行程序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表作業 的當地語系化字串。
        /// </summary>
        public static string 報表作業 {
            get {
                return ResourceManager.GetString("報表作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表排序設定 的當地語系化字串。
        /// </summary>
        public static string 報表排序設定 {
            get {
                return ResourceManager.GetString("報表排序設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 契撤變原因 的當地語系化字串。
        /// </summary>
        public static string 契撤變原因 {
            get {
                return ResourceManager.GetString("契撤變原因", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 契撤變原因列表 的當地語系化字串。
        /// </summary>
        public static string 契撤變原因列表 {
            get {
                return ResourceManager.GetString("契撤變原因列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string 姓名 {
            get {
                return ResourceManager.GetString("姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 委外件數 的當地語系化字串。
        /// </summary>
        public static string 委外件數 {
            get {
                return ResourceManager.GetString("委外件數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 委外案件數 的當地語系化字串。
        /// </summary>
        public static string 委外案件數 {
            get {
                return ResourceManager.GetString("委外案件數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存證信函 的當地語系化字串。
        /// </summary>
        public static string 存證信函 {
            get {
                return ResourceManager.GetString("存證信函", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存證信函P1 的當地語系化字串。
        /// </summary>
        public static string 存證信函P1 {
            get {
                return ResourceManager.GetString("存證信函P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存證信函P2 的當地語系化字串。
        /// </summary>
        public static string 存證信函P2 {
            get {
                return ResourceManager.GetString("存證信函P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存證信函作業 的當地語系化字串。
        /// </summary>
        public static string 存證信函作業 {
            get {
                return ResourceManager.GetString("存證信函作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小計 的當地語系化字串。
        /// </summary>
        public static string 小計 {
            get {
                return ResourceManager.GetString("小計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未輸入年份或月份 的當地語系化字串。
        /// </summary>
        public static string 尚未輸入年份或月份 {
            get {
                return ResourceManager.GetString("尚未輸入年份或月份", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未輸入相關金額 的當地語系化字串。
        /// </summary>
        public static string 尚未輸入相關金額 {
            get {
                return ResourceManager.GetString("尚未輸入相關金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未選擇已結狀態 的當地語系化字串。
        /// </summary>
        public static string 尚未選擇已結狀態 {
            get {
                return ResourceManager.GetString("尚未選擇已結狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未選擇計算比例 的當地語系化字串。
        /// </summary>
        public static string 尚未選擇計算比例 {
            get {
                return ResourceManager.GetString("尚未選擇計算比例", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作年月 的當地語系化字串。
        /// </summary>
        public static string 工作年月 {
            get {
                return ResourceManager.GetString("工作年月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作月 的當地語系化字串。
        /// </summary>
        public static string 工作月 {
            get {
                return ResourceManager.GetString("工作月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已有重覆之名稱,不允許新增 的當地語系化字串。
        /// </summary>
        public static string 已有重覆之名稱 {
            get {
                return ResourceManager.GetString("已有重覆之名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已清償本金累計金額 的當地語系化字串。
        /// </summary>
        public static string 已清償本金累計金額 {
            get {
                return ResourceManager.GetString("已清償本金累計金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已累計清償 的當地語系化字串。
        /// </summary>
        public static string 已累計清償 {
            get {
                return ResourceManager.GetString("已累計清償", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已結 的當地語系化字串。
        /// </summary>
        public static string 已結 {
            get {
                return ResourceManager.GetString("已結", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已結案件 的當地語系化字串。
        /// </summary>
        public static string 已結案件 {
            get {
                return ResourceManager.GetString("已結案件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已結案件列表 的當地語系化字串。
        /// </summary>
        public static string 已結案件列表 {
            get {
                return ResourceManager.GetString("已結案件列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已結案件明細列表 的當地語系化字串。
        /// </summary>
        public static string 已結案件明細列表 {
            get {
                return ResourceManager.GetString("已結案件明細列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已讀 的當地語系化字串。
        /// </summary>
        public static string 已讀 {
            get {
                return ResourceManager.GetString("已讀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年 的當地語系化字串。
        /// </summary>
        public static string 年 {
            get {
                return ResourceManager.GetString("年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年度 的當地語系化字串。
        /// </summary>
        public static string 年度 {
            get {
                return ResourceManager.GetString("年度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年度案件統計 的當地語系化字串。
        /// </summary>
        public static string 年度案件統計 {
            get {
                return ResourceManager.GetString("年度案件統計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年度案件統計表(計至 的當地語系化字串。
        /// </summary>
        public static string 年度案件統計表 {
            get {
                return ResourceManager.GetString("年度案件統計表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年度總計 的當地語系化字串。
        /// </summary>
        public static string 年度總計 {
            get {
                return ResourceManager.GetString("年度總計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        public static string 序號 {
            get {
                return ResourceManager.GetString("序號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建檔人員 的當地語系化字串。
        /// </summary>
        public static string 建檔人員 {
            get {
                return ResourceManager.GetString("建檔人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建檔日期 的當地語系化字串。
        /// </summary>
        public static string 建檔日期 {
            get {
                return ResourceManager.GetString("建檔日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立時間 的當地語系化字串。
        /// </summary>
        public static string 建立時間 {
            get {
                return ResourceManager.GetString("建立時間", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立者姓名 的當地語系化字串。
        /// </summary>
        public static string 建立者姓名 {
            get {
                return ResourceManager.GetString("建立者姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 律師服務費 的當地語系化字串。
        /// </summary>
        public static string 律師服務費 {
            get {
                return ResourceManager.GetString("律師服務費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 律師服務費率 的當地語系化字串。
        /// </summary>
        public static string 律師服務費率 {
            get {
                return ResourceManager.GetString("律師服務費率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 律師服務費編輯 的當地語系化字串。
        /// </summary>
        public static string 律師服務費編輯 {
            get {
                return ResourceManager.GetString("律師服務費編輯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您尚未選擇清償日期 的當地語系化字串。
        /// </summary>
        public static string 您尚未選擇清償日期 {
            get {
                return ResourceManager.GetString("您尚未選擇清償日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應還款累計金額 的當地語系化字串。
        /// </summary>
        public static string 應還款累計金額 {
            get {
                return ResourceManager.GetString("應還款累計金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 承辦人 的當地語系化字串。
        /// </summary>
        public static string 承辦人 {
            get {
                return ResourceManager.GetString("承辦人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 承辦單位 的當地語系化字串。
        /// </summary>
        public static string 承辦單位 {
            get {
                return ResourceManager.GetString("承辦單位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 承辦單位列表 的當地語系化字串。
        /// </summary>
        public static string 承辦單位列表 {
            get {
                return ResourceManager.GetString("承辦單位列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 承辦部室 的當地語系化字串。
        /// </summary>
        public static string 承辦部室 {
            get {
                return ResourceManager.GetString("承辦部室", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string 排序 {
            get {
                return ResourceManager.GetString("排序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序年度 的當地語系化字串。
        /// </summary>
        public static string 排序年度 {
            get {
                return ResourceManager.GetString("排序年度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序設定 的當地語系化字串。
        /// </summary>
        public static string 排序設定 {
            get {
                return ResourceManager.GetString("排序設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序；格式錯誤 的當地語系化字串。
        /// </summary>
        public static string 排序錯誤 {
            get {
                return ResourceManager.GetString("排序錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋條件 的當地語系化字串。
        /// </summary>
        public static string 搜尋條件 {
            get {
                return ResourceManager.GetString("搜尋條件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數入不合法的數值！請重新輸入！ 的當地語系化字串。
        /// </summary>
        public static string 數入不合法的數值 {
            get {
                return ResourceManager.GetString("數入不合法的數值", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增利率 的當地語系化字串。
        /// </summary>
        public static string 新增利率 {
            get {
                return ResourceManager.GetString("新增利率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增契撤變原因 的當地語系化字串。
        /// </summary>
        public static string 新增契撤變原因 {
            get {
                return ResourceManager.GetString("新增契撤變原因", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增律師服務費 的當地語系化字串。
        /// </summary>
        public static string 新增律師服務費 {
            get {
                return ResourceManager.GetString("新增律師服務費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增律師服務費率 的當地語系化字串。
        /// </summary>
        public static string 新增律師服務費率 {
            get {
                return ResourceManager.GetString("新增律師服務費率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增承辦單位 的當地語系化字串。
        /// </summary>
        public static string 新增承辦單位 {
            get {
                return ResourceManager.GetString("新增承辦單位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增清償明細 的當地語系化字串。
        /// </summary>
        public static string 新增清償明細 {
            get {
                return ResourceManager.GetString("新增清償明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增管理人員 的當地語系化字串。
        /// </summary>
        public static string 新增管理人員 {
            get {
                return ResourceManager.GetString("新增管理人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增結案狀態 的當地語系化字串。
        /// </summary>
        public static string 新增結案狀態 {
            get {
                return ResourceManager.GetString("新增結案狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增經辦人員 的當地語系化字串。
        /// </summary>
        public static string 新增經辦人員 {
            get {
                return ResourceManager.GetString("新增經辦人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        public static string 明細 {
            get {
                return ResourceManager.GetString("明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否含當月建檔件 的當地語系化字串。
        /// </summary>
        public static string 是否含當月建檔件 {
            get {
                return ResourceManager.GetString("是否含當月建檔件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否確定停用? 的當地語系化字串。
        /// </summary>
        public static string 是否確定停用 {
            get {
                return ResourceManager.GetString("是否確定停用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否確定啟用? 的當地語系化字串。
        /// </summary>
        public static string 是否確定啟用 {
            get {
                return ResourceManager.GetString("是否確定啟用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新完成 的當地語系化字串。
        /// </summary>
        public static string 更新完成 {
            get {
                return ResourceManager.GetString("更新完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後異動日期 的當地語系化字串。
        /// </summary>
        public static string 最後異動日期 {
            get {
                return ResourceManager.GetString("最後異動日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會辦工作月 的當地語系化字串。
        /// </summary>
        public static string 會辦工作月 {
            get {
                return ResourceManager.GetString("會辦工作月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月 的當地語系化字串。
        /// </summary>
        public static string 月 {
            get {
                return ResourceManager.GetString("月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月份 的當地語系化字串。
        /// </summary>
        public static string 月份 {
            get {
                return ResourceManager.GetString("月份", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 服務費報酬 的當地語系化字串。
        /// </summary>
        public static string 服務費報酬 {
            get {
                return ResourceManager.GetString("服務費報酬", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未結 的當地語系化字串。
        /// </summary>
        public static string 未結 {
            get {
                return ResourceManager.GetString("未結", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未結案 的當地語系化字串。
        /// </summary>
        public static string 未結案 {
            get {
                return ResourceManager.GetString("未結案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未結案件列表 的當地語系化字串。
        /// </summary>
        public static string 未結案件列表 {
            get {
                return ResourceManager.GetString("未結案件列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未結案件明細列表 的當地語系化字串。
        /// </summary>
        public static string 未結案件明細列表 {
            get {
                return ResourceManager.GetString("未結案件明細列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未讀 的當地語系化字串。
        /// </summary>
        public static string 未讀 {
            get {
                return ResourceManager.GetString("未讀", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本月結案 的當地語系化字串。
        /// </summary>
        public static string 本月結案 {
            get {
                return ResourceManager.GetString("本月結案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本次應電催日期期限 的當地語系化字串。
        /// </summary>
        public static string 本次應電催日期期限 {
            get {
                return ResourceManager.GetString("本次應電催日期期限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本金金額 的當地語系化字串。
        /// </summary>
        public static string 本金金額 {
            get {
                return ResourceManager.GetString("本金金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢作業 的當地語系化字串。
        /// </summary>
        public static string 查詢作業 {
            get {
                return ResourceManager.GetString("查詢作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 核扣規費 的當地語系化字串。
        /// </summary>
        public static string 核扣規費 {
            get {
                return ResourceManager.GetString("核扣規費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 案件狀態 的當地語系化字串。
        /// </summary>
        public static string 案件狀態 {
            get {
                return ResourceManager.GetString("案件狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務員 的當地語系化字串。
        /// </summary>
        public static string 業務員 {
            get {
                return ResourceManager.GetString("業務員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 止 的當地語系化字串。
        /// </summary>
        public static string 止 {
            get {
                return ResourceManager.GetString("止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正常 的當地語系化字串。
        /// </summary>
        public static string 正常 {
            get {
                return ResourceManager.GetString("正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此順位已有設定，請重新選擇順位 的當地語系化字串。
        /// </summary>
        public static string 此順位已有設定 {
            get {
                return ResourceManager.GetString("此順位已有設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 法催案件維護逾30日未異動通知 的當地語系化字串。
        /// </summary>
        public static string 法催案件維護逾30日未異動通知 {
            get {
                return ResourceManager.GetString("法催案件維護逾30日未異動通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 法追明細 的當地語系化字串。
        /// </summary>
        public static string 法追明細 {
            get {
                return ResourceManager.GetString("法追明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 法追查詢列表 的當地語系化字串。
        /// </summary>
        public static string 法追查詢列表 {
            get {
                return ResourceManager.GetString("法追查詢列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 法追案件匯入 的當地語系化字串。
        /// </summary>
        public static string 法追案件匯入 {
            get {
                return ResourceManager.GetString("法追案件匯入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 法追統計報表 的當地語系化字串。
        /// </summary>
        public static string 法追統計報表 {
            get {
                return ResourceManager.GetString("法追統計報表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 法院規費 的當地語系化字串。
        /// </summary>
        public static string 法院規費 {
            get {
                return ResourceManager.GetString("法院規費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 注意事項： 的當地語系化字串。
        /// </summary>
        public static string 注意事項 {
            get {
                return ResourceManager.GetString("注意事項", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 注意：1.若不須計算利息，利率請選擇(0)，利息起迄日則不需輸入!並請按下更新按鈕! 的當地語系化字串。
        /// </summary>
        public static string 注意若不須計算利息利率請選擇 {
            get {
                return ResourceManager.GetString("注意若不須計算利息利率請選擇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償利息 的當地語系化字串。
        /// </summary>
        public static string 清償利息 {
            get {
                return ResourceManager.GetString("清償利息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償利息 + 法院規費 + 其他規費 的當地語系化字串。
        /// </summary>
        public static string 清償利息法院規費其他規費 {
            get {
                return ResourceManager.GetString("清償利息法院規費其他規費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償日期 的當地語系化字串。
        /// </summary>
        public static string 清償日期 {
            get {
                return ResourceManager.GetString("清償日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償明細 的當地語系化字串。
        /// </summary>
        public static string 清償明細 {
            get {
                return ResourceManager.GetString("清償明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償本金 的當地語系化字串。
        /// </summary>
        public static string 清償本金 {
            get {
                return ResourceManager.GetString("清償本金", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償金額 的當地語系化字串。
        /// </summary>
        public static string 清償金額 {
            get {
                return ResourceManager.GetString("清償金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 清償金額分別以結案(結欠金額)與未結案之清償金額分別計算後再加總=總清償金額！ 的當地語系化字串。
        /// </summary>
        public static string 清償金額分別以結案 {
            get {
                return ResourceManager.GetString("清償金額分別以結案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償金額跟續佣抵扣不得同時存在 的當地語系化字串。
        /// </summary>
        public static string 清償金額跟續佣抵扣不得同時存在 {
            get {
                return ResourceManager.GetString("清償金額跟續佣抵扣不得同時存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清償金額需等於清償本金 的當地語系化字串。
        /// </summary>
        public static string 清償金額需等於清償本金 {
            get {
                return ResourceManager.GetString("清償金額需等於清償本金", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無實益案件維護作業 的當地語系化字串。
        /// </summary>
        public static string 無實益案件維護作業 {
            get {
                return ResourceManager.GetString("無實益案件維護作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 照會單 的當地語系化字串。
        /// </summary>
        public static string 照會單 {
            get {
                return ResourceManager.GetString("照會單", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 照會單作業-已發送紀錄 的當地語系化字串。
        /// </summary>
        public static string 照會單作業已發送紀錄 {
            get {
                return ResourceManager.GetString("照會單作業已發送紀錄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 照會單號 的當地語系化字串。
        /// </summary>
        public static string 照會單號 {
            get {
                return ResourceManager.GetString("照會單號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 照會編號 的當地語系化字串。
        /// </summary>
        public static string 照會編號 {
            get {
                return ResourceManager.GetString("照會編號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string 狀態 {
            get {
                return ResourceManager.GetString("狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態名稱 的當地語系化字串。
        /// </summary>
        public static string 狀態名稱 {
            get {
                return ResourceManager.GetString("狀態名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態設定 的當地語系化字串。
        /// </summary>
        public static string 狀態設定 {
            get {
                return ResourceManager.GetString("狀態設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 留言對象 的當地語系化字串。
        /// </summary>
        public static string 留言對象 {
            get {
                return ResourceManager.GetString("留言對象", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當月還款明細 的當地語系化字串。
        /// </summary>
        public static string 當月還款明細 {
            get {
                return ResourceManager.GetString("當月還款明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發函金額 的當地語系化字串。
        /// </summary>
        public static string 發函金額 {
            get {
                return ResourceManager.GetString("發函金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發送對象 的當地語系化字串。
        /// </summary>
        public static string 發送對象 {
            get {
                return ResourceManager.GetString("發送對象", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發送日期 的當地語系化字串。
        /// </summary>
        public static string 發送日期 {
            get {
                return ResourceManager.GetString("發送日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 百分比 的當地語系化字串。
        /// </summary>
        public static string 百分比 {
            get {
                return ResourceManager.GetString("百分比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關費率設定 的當地語系化字串。
        /// </summary>
        public static string 相關費率設定 {
            get {
                return ResourceManager.GetString("相關費率設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第一次電催 的當地語系化字串。
        /// </summary>
        public static string 第一次電催 {
            get {
                return ResourceManager.GetString("第一次電催", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第二次電催 的當地語系化字串。
        /// </summary>
        public static string 第二次電催 {
            get {
                return ResourceManager.GetString("第二次電催", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 筆數 的當地語系化字串。
        /// </summary>
        public static string 筆數 {
            get {
                return ResourceManager.GetString("筆數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理人員設定 的當地語系化字串。
        /// </summary>
        public static string 管理人員設定 {
            get {
                return ResourceManager.GetString("管理人員設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統發生錯誤 的當地語系化字串。
        /// </summary>
        public static string 系統發生錯誤 {
            get {
                return ResourceManager.GetString("系統發生錯誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統紀錄Log 的當地語系化字串。
        /// </summary>
        public static string 系統紀錄Log {
            get {
                return ResourceManager.GetString("系統紀錄Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案 的當地語系化字串。
        /// </summary>
        public static string 結案 {
            get {
                return ResourceManager.GetString("結案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案日期 的當地語系化字串。
        /// </summary>
        public static string 結案日期 {
            get {
                return ResourceManager.GetString("結案日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案狀態 的當地語系化字串。
        /// </summary>
        public static string 結案狀態 {
            get {
                return ResourceManager.GetString("結案狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案狀態一旦有案件參考後，不可進行刪除作業 的當地語系化字串。
        /// </summary>
        public static string 結案狀態一旦有案件參考後 {
            get {
                return ResourceManager.GetString("結案狀態一旦有案件參考後", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案狀態列表 的當地語系化字串。
        /// </summary>
        public static string 結案狀態列表 {
            get {
                return ResourceManager.GetString("結案狀態列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案狀態名稱 的當地語系化字串。
        /// </summary>
        public static string 結案狀態名稱 {
            get {
                return ResourceManager.GetString("結案狀態名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案類型 的當地語系化字串。
        /// </summary>
        public static string 結案類型 {
            get {
                return ResourceManager.GetString("結案類型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結欠月 的當地語系化字串。
        /// </summary>
        public static string 結欠月 {
            get {
                return ResourceManager.GetString("結欠月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結欠總金額 的當地語系化字串。
        /// </summary>
        public static string 結欠總金額 {
            get {
                return ResourceManager.GetString("結欠總金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結欠計算方式 的當地語系化字串。
        /// </summary>
        public static string 結欠計算方式 {
            get {
                return ResourceManager.GetString("結欠計算方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1.結欠計算方式會影響 的當地語系化字串。
        /// </summary>
        public static string 結欠計算方式會影響 {
            get {
                return ResourceManager.GetString("結欠計算方式會影響", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結欠金額 的當地語系化字串。
        /// </summary>
        public static string 結欠金額 {
            get {
                return ResourceManager.GetString("結欠金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結欠金額表 的當地語系化字串。
        /// </summary>
        public static string 結欠金額表 {
            get {
                return ResourceManager.GetString("結欠金額表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 給付月份 的當地語系化字串。
        /// </summary>
        public static string 給付月份 {
            get {
                return ResourceManager.GetString("給付月份", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經辦人員設定 的當地語系化字串。
        /// </summary>
        public static string 經辦人員設定 {
            get {
                return ResourceManager.GetString("經辦人員設定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 維護 的當地語系化字串。
        /// </summary>
        public static string 維護 {
            get {
                return ResourceManager.GetString("維護", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 維護作業 的當地語系化字串。
        /// </summary>
        public static string 維護作業 {
            get {
                return ResourceManager.GetString("維護作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總表 的當地語系化字串。
        /// </summary>
        public static string 總表 {
            get {
                return ResourceManager.GetString("總表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總計 的當地語系化字串。
        /// </summary>
        public static string 總計 {
            get {
                return ResourceManager.GetString("總計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 續佣扣抵 的當地語系化字串。
        /// </summary>
        public static string 續佣扣抵 {
            get {
                return ResourceManager.GetString("續佣扣抵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        public static string 職稱 {
            get {
                return ResourceManager.GetString("職稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自辦件數 的當地語系化字串。
        /// </summary>
        public static string 自辦件數 {
            get {
                return ResourceManager.GetString("自辦件數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自辦案件數 的當地語系化字串。
        /// </summary>
        public static string 自辦案件數 {
            get {
                return ResourceManager.GetString("自辦案件數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊案 的當地語系化字串。
        /// </summary>
        public static string 舊案 {
            get {
                return ResourceManager.GetString("舊案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處別 的當地語系化字串。
        /// </summary>
        public static string 處別 {
            get {
                return ResourceManager.GetString("處別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 計算本金 的當地語系化字串。
        /// </summary>
        public static string 計算本金 {
            get {
                return ResourceManager.GetString("計算本金", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 計算比例 的當地語系化字串。
        /// </summary>
        public static string 計算比例 {
            get {
                return ResourceManager.GetString("計算比例", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訴訟程序 的當地語系化字串。
        /// </summary>
        public static string 訴訟程序 {
            get {
                return ResourceManager.GetString("訴訟程序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 說明： 的當地語系化字串。
        /// </summary>
        public static string 說明 {
            get {
                return ResourceManager.GetString("說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 說明-服務費報酬計算方式：(計算本金 - 核扣規費) X 計算比例 的當地語系化字串。
        /// </summary>
        public static string 說明服務費報酬計算方式 {
            get {
                return ResourceManager.GetString("說明服務費報酬計算方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※ 說明：結欠計算方式會影響 的當地語系化字串。
        /// </summary>
        public static string 說明結欠計算方式會影響 {
            get {
                return ResourceManager.GetString("說明結欠計算方式會影響", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勿上傳空檔 的當地語系化字串。
        /// </summary>
        public static string 請勿上傳空檔 {
            get {
                return ResourceManager.GetString("請勿上傳空檔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2‧請勿設定『其他』，此為特定選項供自行輸入。 的當地語系化字串。
        /// </summary>
        public static string 請勿設定其他 {
            get {
                return ResourceManager.GetString("請勿設定其他", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※&amp;nbsp;1.請注意！此舊案件匯入格式多2個欄位：訴訟程序、執行程序！ 的當地語系化字串。
        /// </summary>
        public static string 請注意此舊案件匯入格式多2個欄位訴訟程序執行程序 {
            get {
                return ResourceManager.GetString("請注意此舊案件匯入格式多2個欄位訴訟程序執行程序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入數字! 的當地語系化字串。
        /// </summary>
        public static string 請輸入數字 {
            get {
                return ResourceManager.GetString("請輸入數字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ※請輸入民國年 的當地語系化字串。
        /// </summary>
        public static string 請輸入民國年 {
            get {
                return ResourceManager.GetString("請輸入民國年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string 請選擇 {
            get {
                return ResourceManager.GetString("請選擇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀取紀錄 的當地語系化字串。
        /// </summary>
        public static string 讀取紀錄 {
            get {
                return ResourceManager.GetString("讀取紀錄", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變動 的當地語系化字串。
        /// </summary>
        public static string 變動 {
            get {
                return ResourceManager.GetString("變動", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分證 的當地語系化字串。
        /// </summary>
        public static string 身分證 {
            get {
                return ResourceManager.GetString("身分證", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分證ID 的當地語系化字串。
        /// </summary>
        public static string 身分證ID {
            get {
                return ResourceManager.GetString("身分證ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 追回本金金額 的當地語系化字串。
        /// </summary>
        public static string 追回本金金額 {
            get {
                return ResourceManager.GetString("追回本金金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 追回金額 的當地語系化字串。
        /// </summary>
        public static string 追回金額 {
            get {
                return ResourceManager.GetString("追回金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 追索程序 的當地語系化字串。
        /// </summary>
        public static string 追索程序 {
            get {
                return ResourceManager.GetString("追索程序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通知作業 的當地語系化字串。
        /// </summary>
        public static string 通知作業 {
            get {
                return ResourceManager.GetString("通知作業", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進度表 的當地語系化字串。
        /// </summary>
        public static string 進度表 {
            get {
                return ResourceManager.GetString("進度表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 進行中 的當地語系化字串。
        /// </summary>
        public static string 進行中 {
            get {
                return ResourceManager.GetString("進行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 達成率 的當地語系化字串。
        /// </summary>
        public static string 達成率 {
            get {
                return ResourceManager.GetString("達成率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇合併年度 的當地語系化字串。
        /// </summary>
        public static string 選擇合併年度 {
            get {
                return ResourceManager.GetString("選擇合併年度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇留言對象 的當地語系化字串。
        /// </summary>
        public static string 選擇留言對象 {
            get {
                return ResourceManager.GetString("選擇留言對象", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇管理人員 的當地語系化字串。
        /// </summary>
        public static string 選擇管理人員 {
            get {
                return ResourceManager.GetString("選擇管理人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇經辦人員 的當地語系化字串。
        /// </summary>
        public static string 選擇經辦人員 {
            get {
                return ResourceManager.GetString("選擇經辦人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇類別 的當地語系化字串。
        /// </summary>
        public static string 選擇類別 {
            get {
                return ResourceManager.GetString("選擇類別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，避免影響案件結案狀態之完整性，刪除前請先確認！ 的當地語系化字串。
        /// </summary>
        public static string 避免影響案件結案狀態之完整性 {
            get {
                return ResourceManager.GetString("避免影響案件結案狀態之完整性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金額 的當地語系化字串。
        /// </summary>
        public static string 金額 {
            get {
                return ResourceManager.GetString("金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 錯誤描述 的當地語系化字串。
        /// </summary>
        public static string 錯誤描述 {
            get {
                return ResourceManager.GetString("錯誤描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1. 電話催告作業請至法追進度表中執行，此處僅作催告通知列表，不進行催告作業! 的當地語系化字串。
        /// </summary>
        public static string 電話催告作業請至法追進度表中執行 {
            get {
                return ResourceManager.GetString("電話催告作業請至法追進度表中執行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2. 電話催告審閱完畢請點選更新按鈕，以利紀錄催告通知時間 的當地語系化字串。
        /// </summary>
        public static string 電話催告審閱完畢請點選更新按鈕 {
            get {
                return ResourceManager.GetString("電話催告審閱完畢請點選更新按鈕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話催告通知 的當地語系化字串。
        /// </summary>
        public static string 電話催告通知 {
            get {
                return ResourceManager.GetString("電話催告通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設經辦順位 的當地語系化字串。
        /// </summary>
        public static string 預設經辦順位 {
            get {
                return ResourceManager.GetString("預設經辦順位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 體系名稱 的當地語系化字串。
        /// </summary>
        public static string 體系名稱 {
            get {
                return ResourceManager.GetString("體系名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 體系排序 的當地語系化字串。
        /// </summary>
        public static string 體系排序 {
            get {
                return ResourceManager.GetString("體系排序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 體系排序設定 的當地語系化字串。
        /// </summary>
        public static string 體系排序設定 {
            get {
                return ResourceManager.GetString("體系排序設定", resourceCulture);
            }
        }
    }
}
