//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP.PSL.WorkResources.MeetingMng.Models {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MeetingMngResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeetingMngResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EP.PSL.WorkResources.MeetingMng.Models.MeetingMngResource", typeof(MeetingMngResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 主席 的當地語系化字串。
        /// </summary>
        public static string 主席 {
            get {
                return ResourceManager.GetString("主席", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 以線上留言通知 的當地語系化字串。
        /// </summary>
        public static string 以線上留言通知 {
            get {
                return ResourceManager.GetString("以線上留言通知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改會議 的當地語系化字串。
        /// </summary>
        public static string 修改會議 {
            get {
                return ResourceManager.GetString("修改會議", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳送訊息 的當地語系化字串。
        /// </summary>
        public static string 傳送訊息 {
            get {
                return ResourceManager.GetString("傳送訊息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參加狀態 的當地語系化字串。
        /// </summary>
        public static string 參加狀態 {
            get {
                return ResourceManager.GetString("參加狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只能選取一名主席 的當地語系化字串。
        /// </summary>
        public static string 只能選取一名主席 {
            get {
                return ResourceManager.GetString("只能選取一名主席", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只能選取一名紀錄者 的當地語系化字串。
        /// </summary>
        public static string 只能選取一名紀錄者 {
            get {
                return ResourceManager.GetString("只能選取一名紀錄者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 召集人 的當地語系化字串。
        /// </summary>
        public static string 召集人 {
            get {
                return ResourceManager.GetString("召集人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 召集人亦是會議成員 的當地語系化字串。
        /// </summary>
        public static string 召集人亦是會議成員 {
            get {
                return ResourceManager.GetString("召集人亦是會議成員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行人員 的當地語系化字串。
        /// </summary>
        public static string 執行人員 {
            get {
                return ResourceManager.GetString("執行人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報告部門 的當地語系化字串。
        /// </summary>
        public static string 報告部門 {
            get {
                return ResourceManager.GetString("報告部門", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 場地與設備 的當地語系化字串。
        /// </summary>
        public static string 場地與設備 {
            get {
                return ResourceManager.GetString("場地與設備", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 完成度 的當地語系化字串。
        /// </summary>
        public static string 完成度 {
            get {
                return ResourceManager.GetString("完成度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已回覆不參加人員 的當地語系化字串。
        /// </summary>
        public static string 已回覆不參加人員 {
            get {
                return ResourceManager.GetString("已回覆不參加人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已回覆參加人員 的當地語系化字串。
        /// </summary>
        public static string 已回覆參加人員 {
            get {
                return ResourceManager.GetString("已回覆參加人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立日期 的當地語系化字串。
        /// </summary>
        public static string 建立日期 {
            get {
                return ResourceManager.GetString("建立日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立者 的當地語系化字串。
        /// </summary>
        public static string 建立者 {
            get {
                return ResourceManager.GetString("建立者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成員 的當地語系化字串。
        /// </summary>
        public static string 成員 {
            get {
                return ResourceManager.GetString("成員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋條件 的當地語系化字串。
        /// </summary>
        public static string 搜尋條件 {
            get {
                return ResourceManager.GetString("搜尋條件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增會議 的當地語系化字串。
        /// </summary>
        public static string 新增會議 {
            get {
                return ResourceManager.GetString("新增會議", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期格式有誤，開始日期不能大於等於結束日期 的當地語系化字串。
        /// </summary>
        public static string 日期格式有誤 {
            get {
                return ResourceManager.GetString("日期格式有誤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議衝突，您選擇的會議地點的召開時間已被選用!!無法召開會議!請重新選擇。 的當地語系化字串。
        /// </summary>
        public static string 時間重複 {
            get {
                return ResourceManager.GetString("時間重複", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議列表 的當地語系化字串。
        /// </summary>
        public static string 會議列表 {
            get {
                return ResourceManager.GetString("會議列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議名稱 的當地語系化字串。
        /// </summary>
        public static string 會議名稱 {
            get {
                return ResourceManager.GetString("會議名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議名稱關鍵字 的當地語系化字串。
        /// </summary>
        public static string 會議名稱關鍵字 {
            get {
                return ResourceManager.GetString("會議名稱關鍵字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議地點 的當地語系化字串。
        /// </summary>
        public static string 會議地點 {
            get {
                return ResourceManager.GetString("會議地點", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊會議地點請以欄位【場地與設備】為主！ 的當地語系化字串。
        /// </summary>
        public static string 會議地點請以欄位 {
            get {
                return ResourceManager.GetString("會議地點請以欄位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議狀態 的當地語系化字串。
        /// </summary>
        public static string 會議狀態 {
            get {
                return ResourceManager.GetString("會議狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議詳細資料 的當地語系化字串。
        /// </summary>
        public static string 會議詳細資料 {
            get {
                return ResourceManager.GetString("會議詳細資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議說明 的當地語系化字串。
        /// </summary>
        public static string 會議說明 {
            get {
                return ResourceManager.GetString("會議說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議說明關鍵字 的當地語系化字串。
        /// </summary>
        public static string 會議說明關鍵字 {
            get {
                return ResourceManager.GetString("會議說明關鍵字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會議追蹤事項 的當地語系化字串。
        /// </summary>
        public static string 會議追蹤事項 {
            get {
                return ResourceManager.GetString("會議追蹤事項", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未回覆人員 的當地語系化字串。
        /// </summary>
        public static string 未回覆人員 {
            get {
                return ResourceManager.GetString("未回覆人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇場地與設備，只是單純舉辦會議，並沒有任何場地與設備被預借!不需要請按【確定】鍵;需要請按【取消】鍵返回重新選取!! 的當地語系化字串。
        /// </summary>
        public static string 未選擇場地與設備 {
            get {
                return ResourceManager.GetString("未選擇場地與設備", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 標題 的當地語系化字串。
        /// </summary>
        public static string 標題 {
            get {
                return ResourceManager.GetString("標題", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案上傳者 的當地語系化字串。
        /// </summary>
        public static string 檔案上傳者 {
            get {
                return ResourceManager.GetString("檔案上傳者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案名稱關鍵字 的當地語系化字串。
        /// </summary>
        public static string 檔案名稱關鍵字 {
            get {
                return ResourceManager.GetString("檔案名稱關鍵字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案說明 的當地語系化字串。
        /// </summary>
        public static string 檔案說明 {
            get {
                return ResourceManager.GetString("檔案說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案說明關鍵字 的當地語系化字串。
        /// </summary>
        public static string 檔案說明關鍵字 {
            get {
                return ResourceManager.GetString("檔案說明關鍵字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 決議事項 的當地語系化字串。
        /// </summary>
        public static string 決議事項 {
            get {
                return ResourceManager.GetString("決議事項", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 決議事項標題關鍵字 的當地語系化字串。
        /// </summary>
        public static string 決議事項標題關鍵字 {
            get {
                return ResourceManager.GetString("決議事項標題關鍵字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 決議事項說明關鍵字 的當地語系化字串。
        /// </summary>
        public static string 決議事項說明關鍵字 {
            get {
                return ResourceManager.GetString("決議事項說明關鍵字", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流水號 的當地語系化字串。
        /// </summary>
        public static string 流水號 {
            get {
                return ResourceManager.GetString("流水號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關檔案 的當地語系化字串。
        /// </summary>
        public static string 相關檔案 {
            get {
                return ResourceManager.GetString("相關檔案", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄者 的當地語系化字串。
        /// </summary>
        public static string 紀錄者 {
            get {
                return ResourceManager.GetString("紀錄者", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束日期 的當地語系化字串。
        /// </summary>
        public static string 結束日期 {
            get {
                return ResourceManager.GetString("結束日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯成員需全部成員重選 的當地語系化字串。
        /// </summary>
        public static string 編輯成員需全部成員重選 {
            get {
                return ResourceManager.GetString("編輯成員需全部成員重選", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自定新增會議地點 的當地語系化字串。
        /// </summary>
        public static string 自定新增會議地點 {
            get {
                return ResourceManager.GetString("自定新增會議地點", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自訂選擇會議地點 的當地語系化字串。
        /// </summary>
        public static string 自訂選擇會議地點 {
            get {
                return ResourceManager.GetString("自訂選擇會議地點", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與會人員 的當地語系化字串。
        /// </summary>
        public static string 與會人員 {
            get {
                return ResourceManager.GetString("與會人員", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明 的當地語系化字串。
        /// </summary>
        public static string 說明 {
            get {
                return ResourceManager.GetString("說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請回覆參加狀態或改變會議狀態再點擊送出 的當地語系化字串。
        /// </summary>
        public static string 請回覆參加狀態或改變會議狀態再點擊送出 {
            get {
                return ResourceManager.GetString("請回覆參加狀態或改變會議狀態再點擊送出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入事項說明 的當地語系化字串。
        /// </summary>
        public static string 請輸入事項說明 {
            get {
                return ResourceManager.GetString("請輸入事項說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入會議名稱 的當地語系化字串。
        /// </summary>
        public static string 請輸入會議名稱 {
            get {
                return ResourceManager.GetString("請輸入會議名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入會議說明 的當地語系化字串。
        /// </summary>
        public static string 請輸入會議說明 {
            get {
                return ResourceManager.GetString("請輸入會議說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入檔案說明 的當地語系化字串。
        /// </summary>
        public static string 請輸入檔案說明 {
            get {
                return ResourceManager.GetString("請輸入檔案說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入追蹤事項 的當地語系化字串。
        /// </summary>
        public static string 請輸入追蹤事項 {
            get {
                return ResourceManager.GetString("請輸入追蹤事項", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 追蹤事項 的當地語系化字串。
        /// </summary>
        public static string 追蹤事項 {
            get {
                return ResourceManager.GetString("追蹤事項", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 追蹤事項標題 的當地語系化字串。
        /// </summary>
        public static string 追蹤事項標題 {
            get {
                return ResourceManager.GetString("追蹤事項標題", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期 的當地語系化字串。
        /// </summary>
        public static string 開始日期 {
            get {
                return ResourceManager.GetString("開始日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附件檔 的當地語系化字串。
        /// </summary>
        public static string 附件檔 {
            get {
                return ResourceManager.GetString("附件檔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附加檔案名稱 的當地語系化字串。
        /// </summary>
        public static string 附加檔案名稱 {
            get {
                return ResourceManager.GetString("附加檔案名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        public static string 類別 {
            get {
                return ResourceManager.GetString("類別", resourceCulture);
            }
        }
    }
}
