//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP.SD.Collections.PlanSet.Models {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanSetResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanSetResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EP.SD.Collections.PlanSet.PlanSetResource", typeof(PlanSetResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 MDRT屆數 的當地語系化字串。
        /// </summary>
        public static string MDRT屆數 {
            get {
                return ResourceManager.GetString("MDRT屆數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (預設當月，僅顯示最近6個月，未核實保單) 的當地語系化字串。
        /// </summary>
        public static string Memo_1 {
            get {
                return ResourceManager.GetString("Memo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人年度績效報酬 的當地語系化字串。
        /// </summary>
        public static string 個人年度績效報酬 {
            get {
                return ResourceManager.GetString("個人年度績效報酬", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人達成報酬 的當地語系化字串。
        /// </summary>
        public static string 個人達成報酬 {
            get {
                return ResourceManager.GetString("個人達成報酬", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 初年度服務報酬 的當地語系化字串。
        /// </summary>
        public static string 初年度服務報酬 {
            get {
                return ResourceManager.GetString("初年度服務報酬", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 受理日 的當地語系化字串。
        /// </summary>
        public static string 受理日 {
            get {
                return ResourceManager.GetString("受理日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 屆 的當地語系化字串。
        /// </summary>
        public static string 屆 {
            get {
                return ResourceManager.GetString("屆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 差額 的當地語系化字串。
        /// </summary>
        public static string 差額 {
            get {
                return ResourceManager.GetString("差額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入目標FYC(元) 的當地語系化字串。
        /// </summary>
        public static string 請輸入目標FYC {
            get {
                return ResourceManager.GetString("請輸入目標FYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料日期 的當地語系化字串。
        /// </summary>
        public static string 資料日期 {
            get {
                return ResourceManager.GetString("資料日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預估佣酬試算(元) 的當地語系化字串。
        /// </summary>
        public static string 預估佣酬試算 {
            get {
                return ResourceManager.GetString("預估佣酬試算", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預估保險公司獎勵合計(元) 的當地語系化字串。
        /// </summary>
        public static string 預估保險公司獎勵合計 {
            get {
                return ResourceManager.GetString("預估保險公司獎勵合計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預估合計(元) 的當地語系化字串。
        /// </summary>
        public static string 預估合計 {
            get {
                return ResourceManager.GetString("預估合計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預估計入競賽FYC合計 的當地語系化字串。
        /// </summary>
        public static string 預估計入競賽FYC合計 {
            get {
                return ResourceManager.GetString("預估計入競賽FYC合計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預估試算明細 的當地語系化字串。
        /// </summary>
        public static string 預估試算明細 {
            get {
                return ResourceManager.GetString("預估試算明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預收FYC合計 的當地語系化字串。
        /// </summary>
        public static string 預收FYC合計 {
            get {
                return ResourceManager.GetString("預收FYC合計", resourceCulture);
            }
        }
    }
}
